# .github/workflows/chromatic.yml

name: "Chromatic"

on: push

jobs:
  interaction-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        name: Setup Bun
      - name: Install dependencies
        run: bun install
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build Storybook
        run: bun build-storybook --quiet
      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s last -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006" \
            "npx wait-on tcp:127.0.0.1:6006 --timeout 1m && bun test-storybook"
  visual-tests:
    name: Run Visual Test with Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
        name: Setup Bun
      - name: Install dependencies
        run: bun install
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          # ⚠️ Make sure to configure a `CHROMATIC_PROJECT_TOKEN` repository secret
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}